Repository mzoyinda/RemoteBuddy, pull requests merged in 2022-10, with the labels that each got.

#1 Add layout
  jsconfig.json
  public/index.html
  src/App.css
  src/App.js
  src/assets/maxi-logo.png
  src/assets/mini-logo.png
  src/components/navbar/Navbar.jsx
  src/components/navbar/styles.js
  src/layout/Layout.jsx
  src/layout/styles.js
Labels: enhancement

#2 Oyinda dev
  src/pages/Login.js
Labels: enhancement

#3 Add card container and updated layout
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/assets/buddy.svg
  src/components/button/Back.jsx
  src/components/button/styles.js
  src/components/card/Card.jsx
  src/components/card/styles.js
  src/layout/Layout.jsx
  src/layout/styles.js
  src/pages/Login.js
Labels: enhancement

#4 Added new buddy
  package-lock.json
  package.json
  src/App.js
  src/assets/buddy.svg
  src/pages/Login.js
Labels: enhancement

#6 login assets added
  src/pages/Login.js
Labels: enhancement

#7 fixed framer motion bug
  package-lock.json
  package.json
  src/pages/Login.js
Labels: bug

#8 Add app routing
  src/App.js
  src/index.js
  src/layout/Layout.jsx
  src/pages/Login.js
  src/pages/choose/Choose.jsx
Labels: bug, enhancement

#9 work so far
  src/App.js
  src/layout/Layout.jsx
  src/pages/Login.js
  src/pages/Meetings.js
  src/pages/Music-Choice.js
  src/pages/Remind.js
  src/pages/Welcome.js
  src/pages/choose/Choose.jsx
  src/pages/choose/styles.js
  src/pages/styles.js
Labels: enhancement
